import { defineConfig } from "vitest/config";
import { type Plugin } from "vite";
import react from "@vitejs/plugin-react-swc";

/**
 * Vite plugin to serve runtime config.js in development mode
 * In production, this is generated by docker-entrypoint.sh
 */
function runtimeConfigPlugin(): Plugin {
  return {
    name: "runtime-config",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url === "/config.js") {
          // Serve runtime config from environment variables in dev mode
          const config = `
// Runtime configuration - generated by Vite dev server
window.RUNTIME_CONFIG = {
  FIREBASE_API_KEY: "${process.env.VITE_FIREBASE_API_KEY || ''}",
  FIREBASE_AUTH_DOMAIN: "${process.env.VITE_FIREBASE_AUTH_DOMAIN || ''}",
  FIREBASE_PROJECT_ID: "${process.env.VITE_FIREBASE_PROJECT_ID || ''}",
  FIREBASE_STORAGE_BUCKET: "${process.env.VITE_FIREBASE_STORAGE_BUCKET || ''}",
  FIREBASE_MESSAGING_SENDER_ID: "${process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || ''}",
  FIREBASE_APP_ID: "${process.env.VITE_FIREBASE_APP_ID || ''}",
  FIREBASE_MEASUREMENT_ID: "${process.env.VITE_FIREBASE_MEASUREMENT_ID || ''}",
  API_URL: "${process.env.VITE_API_URL || ''}"
};
`;
          res.setHeader("Content-Type", "application/javascript");
          res.end(config);
          return;
        }
        next();
      });
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), runtimeConfigPlugin()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: "./src/test/setup.ts",
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "lcov", "html"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/main.tsx",
        "src/vite-env.d.ts",
        "src/firebase.ts",
        "src/test/**",
      ],
    },
  },
});
