codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%

flags:
  backend:
    paths:
      - backend/src/
    carryforward: true
  frontend:
    paths:
      - frontend/src/
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  after_n_builds: 2
